kind: Service
apiVersion: v1
metadata:
  name: svcplayer01
  namespace: nsplayer01
spec:
  selector:
    app: web
  type: ClusterIP
  ports:
    - port: 9898
    - targetPort: 9898

---      
kind: Pod
apiVersion: v1
metadata:
  name: web-pod
  namespace: nsplayer01
  labels:
    app: web
spec:
  containers:
    - name: websrv
      image: nginx
