kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: player03-microseg
spec:
  podSelector:
    matchLabels:
      app: player03
  ingress:
   - from:
      - podSelector:
          matchLabels:
            app: player03
