
name: Install nginx ingress controller

# Controls when the action will run.
on:
  # Triggers the workflow on push request on the main branch for changes in the specified paths.
  push:
    branches:
      - main
    paths:
      - '02-init_ingress/**'
      
      # A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # This workflow contains a single job called "build".
  install-ingress:
    # The type of runner that the job will run on.
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
    - name: Checkout master
      uses: actions/checkout@main

    # Install doctl.
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    
    - name: Save DigitalOcean kubeconfig with short-lived credentials
      ##run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ secrets.CLUSTER_NAME }}
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 terraform-do-cluster
        
    - name: deploy 1-click Nginx Ingress Controller
      run: doctl kubernetes 1-click install $(doctl kubernetes cluster get terraform-do-cluster --format ID --no-header) --1-clicks ingress-nginx
      
 
